### ISSUE TITLE
dot and cross product

### ISSUE THREAD

**Issue by nickdesaulniers** [Jam3/math-as-code#6]
Matrix A dot Matrix B

where the dot is usually a small circle (not sure if there's a unicode character for it)

cross product is also a peculiar x, but is not the same as matrix multiplication or component wise multiplication

**Comment by mattdesl** [comment]
Thanks, going to add dot/cross and multiplication notes above sigma.

In a lot of literature I see cross `×` being used to denote matrix multiplication. I have not seen `Matrix A · B` - any chance you can provide some examples? It seems a bit ambiguous - is it a dot product or just regular multiplication?

**Comment by nickdesaulniers** [comment]
A · B is dot product, hence the 'dot operator'
[The name "dot product" is derived from the centered dot " · " that is often used to designate this operation](https://en.wikipedia.org/wiki/Dot_product)

A × B is cross product, see also [its wiki](https://en.wikipedia.org/wiki/Cross_product)

You're right about matrix multiplication being AB vs BA.

I cant remember if component wise multiplication has a symbol, but I also couldn't tell you when it's useful.

**Comment by allo-** [comment]
Componentwise is not used very much in math, because usually you choose the matrix because of the structure (i.e. having matvec and matmat products), not the representation. componentwise would be more like "let c be ``(a_1 b_1, ..., a_n b_n)``" (or maybe ``c_ij = a_ij b=ij`` if you have 2D data for a reason), which does not per se have operations defined on it.

**Comment by mattdesl** [comment]
Yeah, I'm considering moving the element-wise vector multiplication out of that section since Hadamard is very specific and often uses different symbols. 

Otherwise @nickdesaulniers do you think this issue is resolved with dot / cross? I think I will have to deal with matrices in their own section.

**Comment by nickdesaulniers** [comment]
> Otherwise @nickdesaulniers do you think this issue is resolved with dot / cross?

LGTM
