### ISSUE TITLE
Python version?

### ISSUE THREAD

**Issue by rtfisher** [Jam3/math-as-code#61]
I really love this project, and think it could be a fantastic way for math and physics students in particular to become familiar with a programming language.

Any prospect for a Python language version?

**Comment by mattdesl** [comment]
I don’t have the time or desire to rewrite in Python but I will happily link to other language forks in the intro. 😊

**Comment by AlJohri** [comment]
for reference, you can use something like this to add python right into the existing README:

```
<details>
  <summary>Click to expand</summary>
  whatever
</details>
```

renders like:

<details>
  <summary>See Python implementation</summary>

  ---
  ```python
  1 + 1
  ```
  ![sample picture](https://avatars3.githubusercontent.com/u/37498331?s=88&v=4 "Picture")
  ---

  ...a collapsible block
</details>

**Comment by mraza007** [comment]
Who’s working on this issue

**Comment by mraza007** [comment]
I was thinking to create a python version of this

**Comment by stuaxo** [comment]
Fantastic idea - a python version should probably use jupyter notebooks.

**Comment by mraza007** [comment]
Sounds like an idea how should I begin should I start a jupyter notebook specifically for this

**Comment by stuaxo** [comment]
OK... I actually take that back, just porting the README.md would make more sense, you could certainly use a notebook to check the work.

**Comment by mraza007** [comment]
Oh okay I'll begin work on this soon

**Comment by quinn-dougherty** [comment]
Hi, I'm more than happy to knock this out. I'd probably make a file called `PYTHON-README.md` that starts with the original readme, replace all the javascript with python, with few embellishments as they're called for (for instance in python it's important to point out the difference between the vectorization DSL and a vanilla python list). 

a `.ipynb` would be nice, especially with Latex, but since github viewer fails to load `.ipynb` files sometimes (making the user go into colab) and can be particularly hard to read on mobile, it's not obvious that it's the preferred choice. 

but it would be trivial to just to both :) 

@mraza007 how is your fork going? 

Any extra formatting notes or approaches you'd prefer, i'm happy to abide. 

I can send PR in a few days.

**Comment by mraza007** [comment]
Hey @quinn-dougherty  I think its a great Idea I started a seperate repo for python but haven't really done much. I will start working on this after my finals maybe we can split up the load and work together on this

**Comment by quinn-dougherty** [comment]
I ended up finding more time today than i anticipated and [it's all done](https://github.com/Jam3/math-as-code/pull/74)

Sorry Mraza007. 

I stopped short of adding a matrix multiplication section, but I hope I covered everything that was expected :smile_cat:

**Comment by mattdesl** [comment]
Thanks @quinn-dougherty! Merged in. Also open to any more PRs to fix the Python version or link to it from the main.
